services:
  database:
    image: "mariadb:latest"
    container_name: "mariadb-projekt_po"
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
